### ISSUE TITLE
Unsupported browser detection/redirect

### ISSUE THREAD

**Issue by edoardolunardi** [madebywild/wild-next#51]

**Comment by r0skar** [comment]
Next's built-in redirect feature looks like the best candidate for it. Especially since [10.2](https://nextjs.org/blog/next-10-2#header-cookie-and-query-matching-for-rewrites-and-redirects).

**Comment by edoardolunardi** [comment]
@r0skar yep, that's pretty new. So should we combine that with a lib that already contains user agents in a more readable way? Like I've been using [bowser](https://github.com/lancedikson/bowser) lately, but it gave me some problems with in-app browsers.

We usually provide the client a list of browsers our application will support, so what approach do you suggest? Detect the ones we don't support, or detect the ones we do support?

**Comment by r0skar** [comment]
- no need for a lib when its just a list a user-agents
- it should detected unsupported browsers and redirect those (aka a black list and not a white list)

**Comment by edoardolunardi** [comment]
Yeah I agree it should be a black list but, are we gonna look for every possible browser and blacklist it it's not included in the supported ones? 😅 Or just blacklist the most used ones that we don't support?

**Comment by r0skar** [comment]
Imo we should blacklist the ones we know for sure are not working. If we then still get bug reports for a specific browser, we can check it ourselves and eventually add it to the blacklist or fix the issue that was holding it back from being usable.

**Comment by r0skar** [comment]
I have been experimenting a bit with the new redirect feature, but I have a hard time constructing a Regex that matches the browsers we want to exclude. So far, I have:

`".*((Firefox/(([0-5])|(6[0-2])))|((Chromium|Chrome)/([0-6]))|(Trident/7.0)|(Trident/6.0)|(Trident/5.0)|(Trident/4.0)|(([MS]?IE) (5.5|([6-9]|1[0-1]).0))|(Version/(3|(4|5)|5|6|7|(8|9)|9|10|(11.[0-2])).+(?:.d+)? Safari/)).*"`

This works for Firefox < 62, Chrome < 70, all IEs, Safari < 11.2. However, there is still a lot of work to do to make sure we dont include false-positives and to look at the whole mobile market (Android Chrome, Safari Mobile etc.).

**Comment by edoardolunardi** [comment]
@lorenzomigliorero what's your opinion on this point?

**Comment by lorenzomigliorero** [comment]
I also would choose a blacklist approach, check all the supported browsers it's basically impossible to maintain.

More in general, I've always preferred _feature-detection_ over _browser-detection_.
It's more secure and robust, as well as easy to maintain.
UA sniffing always leads to false positives, as well as having to deal with complex error-prone regexes.

Feature-detection obviously can be implemented only client-side, but this is also an advantage because it makes it compatible with static applications.

A possible idea could be the implementation of a custom package configurable on the project needs, which redirects to an external page (or even better show a customizable overlay) after the check of a set of features.

This could be implemented as a web component or in vanilla js because it must be triggered outside and before the React application.

```js
<script src="https://cdn.example.com/@wild/feature-detection.js?css=grid,flex&js=resize-observer,web-socket" />
```

And inside the module, we can use `CSS.supports` API for feature detection:

`CSS.supports("display: flex")`
`CSS.supports("display: grid")`
`typeof window.ResizeObserver !== "undefined"`
`typeof window.WebSocket !== "undefined"`

What do you think about it?

**Comment by edoardolunardi** [comment]
I totally agree with skipping completely the react application when detecting, like I was doing in the latest projects. And I also like feature detection rather than user agent sniffing (or idk if this is really a feature detection, but I prefer to detect IE11 like this `!!document.documentMode` rather than with the user agent)

**Comment by r0skar** [comment]
I agree with feature detection. Also, if we had to do user agent parsing, I more and more think we would want to do it on a server level (nginx) anyway. The new redirect feature in NextJs is nice, but after using it a bit, it feels its not robust enough for our needs.

**Comment by lorenzomigliorero** [comment]
Yeah, I think was made primarily for localizations redirect, and then adapted to other use-cases.
Ok, great, this could be another package for our private registry.

The unique roadblock I see is that the package needs to be hosted on a public CDN.
Is there something available in WILD now?

**Comment by r0skar** [comment]
I will leave this here as a reference: redirect old browsers on the server side (nginx).
Note: the browsers in this list are just an example.

```nginx
map $http_user_agent $outdated {
    default                                 0;
    "~MSIE [1-9]\."                         1;
    "~Mozilla.*Firefox/[1-9]\."             1;
    "~Opera.*Version/[0-9]\."               1;
    "~AppleWebKit.*Version/[0-6]\..*Safari" 1;
    "~Chrome/[0-9]\."                       1;
}

if ($outdated = 1){
    rewrite ^ /outdated redirect;
}
```
