### ISSUE TITLE
NPM or Yarn?

### ISSUE THREAD

**Issue by lorenzomigliorero** [madebywild/wild-next#55]
Hey guys,

I saw that npm is widely used in our projects.

I would like to understand if there are technical reasons behind this choice, or if it is something we can change for future projects.

I personally prefer Yarn:

- It's quickly than NPM in dependencies resolutions
- It offers a more completed upgrade command (`yarn upgrade-interactive` is really easy to use)
- built-in `yarn why` command, very useful to identify multiple version of the same package, detailing which other packages depend upon it
- since yarn 1.0,  yarn.lock conflicts are automatically resolved by yarn https://dev.to/brettimus/let-yarn-resolve-your-conflicts-3jbb
- yarn’s output is cleaner and less verbose
- probably yarn offers a more stable "workspaces" support, but I saw that even NPM has it since 7.0

In general, I think we could be evaluate yarn for future projects.
We can also organize a mini-workshop to share the behavior of the more useful commands.

What's your opinion on that?

**Comment by r0skar** [comment]
Some random thoughts:
- npm is more popular and the defacto default (lots of examples, codeboxes etc. will use npm)
- yarn still feels faster (although npm has caught up by a bit)
- having a native way to do interactive upgrades with yarn is great and we can get rid of npm utils (`npm-upgrade` or w/e)
- i have been used yarn in the past and never run into an issue. i did run into occasional issues with npm.

Overall, I'd be very much in favor of trying it out in future projects and then decide to make the switch or not.

p.s. for any1 curious, checkout the [yarn branch](https://github.com/madebywild/wild-next/tree/build/yarn)

**Comment by stefan-wild** [comment]
I have to confess, I've never used fancier features of either (beside like outdated or audit in npm), and both worked fine for me so far

Mostly people here used whatever they prefered, until one project suddendly stopped working with npm but worked with yarn. Then the consensus was, that we should only have one, and npm was alright and already there


but in general, I'm more in favor of keeping the delta between projects small, since quite often here

-  old sites need updates
- you're working on mutliple projects at the same time
- sites are hosted on all kinds of servers

and then you have to consider each time, which one you should be using or if there's an extra step with site setups
and I'm not sure if the upsides are big enough (if wild keeps working on a lot of smaller projects)

**Comment by r0skar** [comment]
We will keep using npm for the foreseeable future.
